const express=require("express")
const app=express()
const fileUpload= require('express-fileupload')
app.use(express.json({limit:'50mb'}))
app.use(fileUpload({useTempFiles:true}))
const router=require("./Routes/route")
const mongoose=require("mongoose")
const cors=require("cors")
require("dotenv").config()
 app.use(cors({origin:"http://localhost:3000"}))
mongoose.connect(process.env.URL,()=>console.log("database is connected"))
const posterRouter=require("./Routes/postRoute")
app.use("/",router)
app.use("/",posterRouter)
app.listen(8081,()=>console.log("server is running.."))

